# Generated by Django 5.1.7 on 2025-04-04 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='sigla',
            field=models.CharField(blank=True, help_text='Sigla do serviço (ex: RE, BA)', max_length=3, null=True, unique=True),
        ),
    ]
