# Generated by Django 5.1.7 on 2025-04-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0002_servico_sigla'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='periodo',
            field=models.CharField(blank=True, choices=[('manha', 'Manhã (07h-13h)'), ('tarde', 'Tarde (13h-19h)')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='atendimento',
            name='tempo_atendimento',
            field=models.IntegerField(blank=True, help_text='Tempo de atendimento em minutos', null=True),
        ),
        migrations.AlterField(
            model_name='servico',
            name='sigla',
            field=models.CharField(blank=True, help_text='Sigla do serviço (ex: BU, BA)', max_length=3, null=True, unique=True),
        ),
    ]
