# Generated by Django 5.1.7 on 2025-04-04 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0003_atendimento_periodo_atendimento_tempo_atendimento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='ultimo_numero',
            field=models.IntegerField(default=0, help_text='Último número de senha usado para este serviço'),
        ),
    ]
