# Generated by Django 5.2 on 2025-05-05 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0004_servico_ultimo_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('chamado', 'Chamado'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado')], default='pendente', max_length=20),
        ),
    ]
