# Generated by Django 5.2 on 2025-05-05 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0005_alter_atendimento_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('chamado', 'Chamado'), ('finalizado', 'Finalizado')], default='pendente', max_length=20),
        ),
    ]
