# Generated by Django 5.2 on 2025-05-05 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atendimentos', '0006_alter_atendimento_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='atendimento',
            name='inicio_em',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='atendimento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Pendente'), ('chamado', 'Chamado'), ('em_atendimento', 'Em Atendimento'), ('finalizado', 'Finalizado')], default='pendente', max_length=20),
        ),
    ]
